# Generated by Django 5.1.7 on 2025-04-08 16:00

import apps.accounts.managers
import django.db.models.deletion
import django.utils.timezone
import apps.commons.model_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', apps.commons.model_fields.CharFieldNoEmptyString(max_length=11, unique=True)),
                ('username', apps.commons.model_fields.CharFieldNoEmptyString(blank=True, null=True, unique=True)),
                ('password', apps.commons.model_fields.CharFieldNoEmptyString(blank=True, null=True, unique=True)),
                ('email', apps.commons.model_fields.EmailFieldNoEmptyString(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('OPERATOR', 'Operator'), ('STUDENT', 'Student')], default='STUDENT', max_length=8)),
                ('is_active', models.BooleanField(default=False)),
                ('profile_completed', models.BooleanField(default=False)),
                ('group', models.ManyToManyField(blank=True, related_name='accounts', to='auth.group')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='accounts', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', apps.accounts.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('education', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('national_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('acquisition', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
