# Generated by Django 5.1.7 on 2025-04-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_completed',
        ),
    ]
