# Generated by Django 5.1.7 on 2025-05-03 12:57

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='questions.tag')),
            ],
            options={
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_body', models.TextField()),
                ('choice_1', models.CharField(max_length=255)),
                ('choice_2', models.CharField(max_length=255)),
                ('choice_3', models.CharField(max_length=255)),
                ('choice_4', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('true_choice', models.CharField(choices=[('choice_1', 'Choice 1'), ('choice_2', 'Choice 2'), ('choice_3', 'Choice 3'), ('choice_4', 'Choice 4')], max_length=20)),
                ('answer', models.TextField(blank=True, null=True)),
                ('hardness', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='questions.tag')),
            ],
        ),
    ]
