# Generated by Django 5.1.7 on 2025-05-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='direction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
