# Generated by Django 5.1.7 on 2025-05-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='min_required_age',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
