# Generated by Django 5.1.7 on 2025-05-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_min_required_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='direction',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
