# Generated by Django 5.1.7 on 2025-05-03 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('journey_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('analytical', 'هوش و استعداد تحلیلی'), ('speed_focus', 'سرعت، دقت و تمرکز')], max_length=20)),
                ('time_minutes_limit', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('question_count_limit', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('answer_result', models.CharField(choices=[('C', 'Correct'), ('F', 'False'), ('N', 'Not Selected')], default='N', max_length=20)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='journies.journey')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_steps', to='questions.question')),
            ],
        ),
    ]
