# Generated by Django 5.1.7 on 2025-05-07 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journies', '0001_initial'),
        ('questions', '0002_alter_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('time_minutes_limit', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('journey_type', models.CharField(choices=[('training', 'آموزشی'), ('exam', 'آزمون استاتیک'), ('group_exam', 'آزمون استاتیک گروهی')], default='training', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='journey_type',
            field=models.CharField(choices=[('training', 'آموزشی'), ('exam', 'آزمون استاتیک'), ('group_exam', 'آزمون استاتیک گروهی')], default='training', max_length=30),
        ),
        migrations.AlterField(
            model_name='journey',
            name='subject',
            field=models.CharField(blank=True, choices=[('analytical', 'هوش و استعداد تحلیلی'), ('speed_focus', 'سرعت، دقت و تمرکز')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='JourneyStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='questions.question')),
                ('journey_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_steps', to='journies.journeytemplate')),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='journey_static',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='journies.journeytemplate'),
        ),
    ]
