# Generated by Django 5.1.7 on 2025-05-08 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journies', '0002_journeytemplate_journey_journey_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='journey_type',
            field=models.CharField(blank=True, choices=[('training', 'آموزشی'), ('exam', 'آزمون استاتیک'), ('group_exam', 'آزمون استاتیک گروهی')], default='training', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='JourneyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('unanswered_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('correct_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('wrong_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_participants', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='journies.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
