# Generated by Django 5.1.7 on 2025-05-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journies', '0003_alter_journey_journey_type_journeyresult'),
        ('questions', '0002_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journeystep',
            options={'ordering': ['step_id']},
        ),
        migrations.AlterModelOptions(
            name='journeysteptemplate',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='journeystep',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='journeystep',
            name='shown_at',
        ),
        migrations.RemoveField(
            model_name='journeystep',
            name='time_taken',
        ),
        migrations.AlterUniqueTogether(
            name='journeysteptemplate',
            unique_together={('journey_template', 'question')},
        ),
    ]
