# Generated by Django 5.1.7 on 2025-05-17 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journies', '0004_alter_journeystep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='last_seen_journey_step',
            field=models.ForeignKey(blank=True, default=None, help_text='The most recent JourneyStep this Journey has seen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='journies.journeystep'),
        ),
    ]
