# Generated by Django 5.1.7 on 2025-05-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journies', '0005_journey_last_seen_journey_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='answered_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='correct_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='rank',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='total_participants',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='unanswered_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='wrong_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='JourneyResult',
        ),
    ]
