# Generated by Django 5.1.7 on 2025-05-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journies', '0006_journey_answered_count_journey_correct_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
