# Generated by Django 5.1.7 on 2025-05-21 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journies', '0007_journey_score'),
        ('questions', '0005_alter_question_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystep',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_steps', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='journeysteptemplate',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz', to='questions.question'),
        ),
    ]
